### ISSUE TITLE
LiDOG Script Failed to Run | ArcGIS PRO 2.4

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiDOG#3]
LiDOG script is failing.  Message below:

**UPDATE:  I placed the MHW dem I was working on at the following location:
\\ngs-s-rsd\Lidar_Contract00\MD1702\lidar\DEMS_LiDOG**

_Messages
Start Time: Monday, February 3, 2020 6:04:23 PM
Running script LiDOG...
************************************************************ (source DEM 1 of 1)
determining coverage of DEM...
md1702_mhw_1m_dem.tif coverage intersects 2 band-4 cell(s)
---------------------------------------- (DEM cell 1 of 2)
processing band-4 product cell US4VA1FE...
clipping md1702_mhw_1m_dem.tif with US4VA1FE cell buffer...
Failed script LiDOG...
 Traceback (most recent call last):
  File "D:\004085819_data\python\LiDOG-1.2.2\scripts\LiDOG.py", line 748, in <module>
    lidog.product_cells[cell_name].clip_src_dem(src_dem)
  File "D:\004085819_data\python\LiDOG-1.2.2\scripts\LiDOG.py", line 303, in clip_src_dem
    self.mask_dem(dem.path, cell_geom, clipped_dem_path)
  File "D:\004085819_data\python\LiDOG-1.2.2\scripts\LiDOG.py", line 272, in mask_dem
    proj4_crs = pyproj.Proj(init=out_crs).definition_string()
  File "C:\Users\Jamie.Kum\.conda\envs\LiDOG\Lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no arguments in initialization list'
 Failed to execute (LiDOG).
Failed at Monday, February 3, 2020 6:04:34 PM (Elapsed Time: 10.64 seconds)_

Running ArcGIS PRO 2.4

**Comment by forkozi** [comment]
The issue is that LiDOG assumes the Python env path to be C:\users\<user>\AppData\Local\Continuum\anaconda3, but the user's Python env path was something else.  I advised the user to modify the conda_dir path in the set_env_vars function.  I updated the docs with a note describing this.
